a = input('digite algo')
print(type(a))
print('Só espaços?', a.isspace)
print('É um número?', a.isnumeric)
print('É alfabético?', a.isalpha)
print('É alfanumérico?', a.isalnum)
print('Está em maiúculas?', a.isupper)
print('Está em minusculas?', a.islower)
print('Está capitalizada', a.istitle)